# settings3.yaml -- the basic setup of the test site
# change to start a new site

siteLayout:
    themeDir:  /home/frank/Workspace11/daino/docs/theme
    # used to place a link to theme in dough/resources
    doughDir: /home/frank/Workspace11/daino/docs/site/dough
    bakedDir: /home/frank/bakedTestSite
    # bakedDir: /home/frank/Workspace11/daino/docs/site/baked
    reportFile: /home/frank/dainoReport.txt
    testDir: /home/frank/.daino 
    # masterTemplateFile: master6.dtpl  #in themeDir
    masterTemplateFile: master7tufte.dtpl  #in themeDir
    # change is global for the site, not per page TODO?
    # doNotPublish: "DNB"
    # todo seems not to work. but entry here is required
    blogAuthorToSuppress: 
      - "AOS"
      - "Author of Settings"     
    # create dir in ExampleTesting
    # filename must be homedir + program name (in Foundation) - hidden
    # fixed in testharness
#    uploadServer: "sgg.gerastree.at"

# add a default biblio file? resources/BibTexLatex.bib
    
    # needs link in resources/templates to themes/templates
localhostPort: 3000

#quotes: True 
# css :
#     - /templates/static/style.css  # relative to root of site - so called absolute
#     - /templates/static/menu.css 
#   values taken from page3/yaml

# content for landing page
settingsAuthor : Author of Settings 
settingsDate: 2019-01-01

siteHeader : 
    sitename : siteName3
    byline : siteByLine3 
    # banner: /resources/templates/img/symmetricGeras2.jpg  
    banner: /resources/theme/templates/img/DSC04809.JPG
    bannerCaption: "Ruhiger Sommer im Garten in Geras"
    # keywords ??

menuitems:
    menuNav:
     # navlink must not start with /
     # and should reference an index.html file (not .md)
      - navlink: ReadMe/index.html
        navtext: ReadMe
      - navlink: Contact/index.html
        navtext: Contact
      - navlink: Blog/index.html
        navtext: Blog
      - navlink : PublicationList/index.html
        navtext : Publications
      # - navlink : dainodesign/index.html
      #   navtext : daino Documentation  


