# settings3.yaml -- the basic setup of the test site
# change to start a new site

siteLayout:
    themeDir:  /home/frank/Workspace11/u4blog/uniform-pandoc/theme
    # was -- /home/frank/Workspace11/dainoTheme
    # must be dir (not including templates)
    # used to place a link to theme in dough/resources
    doughDir: /home/frank/Workspace11/dainoSite 
    bakedDir: /home/frank/bakedTestSite
    # bakedDir: /home/frank/Workspace11/daino/docs/site/baked
    reportFile: /home/frank/dainoReport.txt
    testDir: /home/frank/.daino 
    # masterTemplateFile: master6.dtpl  #in themeDir
    masterTemplateFile: htmlTufte63.dtpl  #in themeDir
    texTemplateFile: latexTufte63.dtpl
    # texTemplateFile: latex7.dtpl # for non-tufte layout 
         # (footnotes at bottom of page)
    # change is global for the site, not per page TODO?
    doNotBake: "DNB"
    # todo seems not to work. but entry here is required
    blogAuthorToSuppress: 
      - "AOS"
      - "AUF"
      - "Author of Settings"   
    defaultAuthor: "AOS" 
    replaceErlaubtFile: "/home/frank/Workspace11/replaceUmlaut/nichtUmlaute.txt"
    # the file with permitte words not to replace
    # defaultBibliography: "resources/BibTexLatex.bib"
    # todo the bibliography is not defaulted because the value must be read by pandoc

    # create dir in ExampleTesting
    # filename must be homedir + program name (in Foundation) - hidden
    # fixed in testharness
#    uploadServer: "sgg.gerastree.at"

# add a default biblio file? resources/BibTexLatex.bib
    
    # needs link in resources/templates to themes/templates
localhostPort: 3000

#quotes: True 
# css :
#     - /templates/static/style.css  # relative to root of site - so called absolute
#     - /templates/static/menu.css 
#   values taken from page3/yaml

# content for landing page
settingsAuthor : Author of Settings 
settingsDate: 2019-01-01

siteHeader : 
    sitename : siteName3
    byline : siteByLine3 
    # banner: /resources/templates/img/symmetricGeras2.jpg  
    banner: /resources/theme/templates/img/DSC04809.JPG
    bannerCaption: "Ruhiger Sommer im Garten in Geras"
    # keywords ??

menuitems:
    menuNav:
     # navlink must not start with /
     # and should reference an index.html file (not .md)
      - navlink: ReadMe/index.html
        navtext: ReadMe
      - navlink: DainoDesign/index.html
        navtext: Rationale
      - navlink: Contact/index.html
        navtext: Contact
      - navlink: Blog/index.html
        navtext: Blog
      - navlink: SimpleTest/index.html
        navtext: Test
      - navlink : PublicationList/index.html
        navtext : Publications
      # - navlink : dainodesign/index.html
      #   navtext : daino Documentation  


