# settings3.yaml -- the basic setup of the test site
# v0.1.6.6 tufte64_26latex - both column close to same size
# requiores af_tufte_common.def and af_tufte.cls in ~/texfm/latex/ 
# run texhas!

siteLayout:
    themeDir: /home/frank/Workspace11/daino/theme
    # must be dir (not including templates)
    # used to place a link to theme in dough/resources
    doughDir: /home/frank/Workspace11/dainoSite 
    bakedDir: /home/frank/bakedTestSite
    reportFile: /home/frank/dainoReport.txt
    testDir: /home/frank/.daino 
    htmlTemplateFile: pandoc64html.dtpl  # from default.html5
    latexTemplateFile: pandoc64latex.dtpl  # from default319latex
         # (footnotes at bottom of page)
    tufteHtmlTemplateFile:  tufte64html.dtpl
    # tufteLatexTemplateFile: tufte64latdirex.dtpl
    tufteLatexTemplateFile: tufte64_26latex.dtpl #fuer WO buch
    doNotBake: "DNB"
    blogAuthorToSuppress: 
      - "AOS"
      - "AUF"
      - "Author of Settings"   
    defaultAuthor: "AOS" 
    replaceErlaubtFile: "/home/frank/Workspace11/replaceUmlaut/nichtUmlaute.txt"
    # the file with permitte words not to replace
    # defaultBibliography: "resources/BibTexLatex.bib"
    # todo the bibliography is not defaulted because the value must be read by pandoc when a booklet is produced independent of daino processing

# add a default biblio file? resources/BibTexLatex.bib
    
localhostPort: 3003

#quotes: True 
# css :
#     - /templates/static/style.css  # relative to root of site - so called absolute
#     - /templates/static/menu.css 
#   values taken from page3/yaml

# content for landing page
settingsAuthor : Author of Settings 
settingsDate: 2019-01-01

siteHeader : 
    sitename : siteName3
    byline : siteByLine3 
    # banner: /resources/templates/img/symmetricGeras2.jpg  
    banner: /resources/theme/templates/img/DSC04809.JPG
    bannerCaption: "Ruhiger Sommer im Garten in Geras"
    # keywords ??

menuitems:
    menuNav:
     # navlink must not start with /
     # and should reference an index.html file (not .md)
      - navlink: ReadMe/index.html
        navtext: ReadMe
      - navlink: DainoDesign/index.html
        navtext: Rationale
      - navlink: Contact/index.html
        navtext: Contact
      - navlink: Blog/index.html
        navtext: Blog
      - navlink: Minimal/index.html
        navtext: Minimal
      - navlink: BookletExample/index.html
        navtext: BookletExample
      - navlink: BookExample/index.html
        navtext: BookExample
      # - navlink : PublicationList/index.html
      #   navtext : Publications
      # - navlink : dainodesign/index.html
      #   navtext : daino Documentation  

